### ISSUE TITLE
Add Github pages

### ISSUE THREAD

**Issue by jcubic** [antonio-m-o-costa/p5js-template#1]
I would be nice if you can actually see the code for yourself not only a screenshot.
If you don't know how you can Google "How to add GitHub pages" I will not give you a specific link just find an article or video that you like.

**Comment by antonio-m-o-costa** [comment]
For som reason I didn't even remember that this repo could be easily used as a GitHub page.
Will add that section to the `README.md` file.

**Comment by antonio-m-o-costa** [comment]
- GitHub pages added to the repository.
- Hosting Preview links added to `README.md` before "Example images".

Additional:
Updated "How to use": Setting container `<div>` for rendering.

**Comment by antonio-m-o-costa** [comment]
- GitHub pages added to the repository.
- Hosting Preview links added to `README.md` before "Example images".

Additional:
Updated "How to use": Setting container `<div>` for rendering.

**Comment by jcubic** [comment]
I didn't mean to add documentation how to use on GitHub pages but so you publish as GitHub pages so you can have link to see the code in action. No one will fork the repo to see how it works.

**Comment by antonio-m-o-costa** [comment]
I later understood later what you meant, but I added it anyway 😅 after I enabled the GH pages.
